# Generated by Django 3.0.2 on 2020-02-01 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_auto_20200201_0704'),
    ]

    operations = [
        migrations.CreateModel(
            name='remarks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CompanyName', models.CharField(max_length=100)),
                ('remark', models.TextField()),
            ],
        ),
    ]
