# Generated by Django 3.0.2 on 2020-02-02 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0003_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='remarks',
            name='company',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='diary.company'),
        ),
    ]
