# Generated by Django 3.0.2 on 2020-02-02 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0005_remove_company_remarks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remarks',
            name='CompanyName',
        ),
    ]
