# Generated by Django 3.0.2 on 2020-02-02 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0006_remove_remarks_companyname'),
    ]

    operations = [
        migrations.AddField(
            model_name='remarks',
            name='datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
