# Generated by Django 3.0.2 on 2020-02-14 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0008_remarks_cpoc'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='placement',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
