# Generated by Django 3.0.2 on 2020-02-15 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0009_company_placement'),
    ]

    operations = [
        migrations.CreateModel(
            name='row_base',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TopRemark', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='diary.remarks')),
                ('company', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='diary.company')),
            ],
        ),
    ]
