# Generated by Django 3.0.2 on 2020-02-15 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0010_row_base'),
    ]

    operations = [
        migrations.DeleteModel(
            name='row_base',
        ),
    ]
