# Generated by Django 3.0.2 on 2020-02-15 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0011_delete_row_base'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='TopRemark',
            field=models.TextField(default='NULL'),
            preserve_default=False,
        ),
    ]
